Условие 1:
Оформляйте ноутбук, используя эти советы:
Номер задачи - заголовок 2
Номер подзадачи - заголовок 3
Предоставленные наборы данных оформляйте, как код
Рекомендации для преподавателей по оценке задания:
Смотреть, чтобы студент красиво оформлял ноутбук, использовал ячейки с текстом, указывал номера заданий

# Задача 1 #

#### На складе лежат разные фрукты в разном количестве. Нужно написать функцию, которая на вход принимает любое количество названий фруктов и их количество, а возвращает общее количество фруктов на складе

In [4]:
fruits = ['pineapples', 'bananas', 'lemons', 'apples', 'pears']
quantity = [100, 150, 85, 420, 200]

In [5]:
total_list = {f: quantity[q] for q, f in enumerate(fruits)}

In [6]:
total_list

{'pineapples': 100, 'bananas': 150, 'lemons': 85, 'apples': 420, 'pears': 200}

In [7]:
sum(quantity)

955

# Задача 2

#### Дан список с затратами на рекламу. Но в данных есть ошибки, некоторые затраты имеют отрицательную величину. Удалите такие значения из списка и посчитайте суммарные затраты
#### [100, 125, -90, 345, 655, -1, 0, 200]
#### Используйте list comprehensions

In [8]:
list_pay = [100, 125, -90, 345, 655, -1, 0, 200]

In [9]:
def new_list_pay(pay):
    return pay if pay > 0 else 0

new_pay = [new_list_pay(i) for i in list_pay]
new_pay

[100, 125, 0, 345, 655, 0, 0, 200]

In [10]:
sum(new_pay)

1425

# Задача 3

## Даны два списка.
* Дата покупки
['2021-09-14', '2021-12-15', '2021-09-08', '2021-12-05', '2021-10-09', '2021-09-30', '2021-12-22', '2021-11-29', '2021-12-24', '2021-11-26', '2021-10-27', '2021-12-18', '2021-11-09', '2021-11-23', '2021-09-27', '2021-10-02', '2021-12-27', '2021-09-20', '2021-12-13', '2021-11-01', '2021-11-09', '2021-12-06', '2021-12-08', '2021-10-09', '2021-10-31', '2021-09-30', '2021-11-09', '2021-12-13', '2021-10-26', '2021-12-09']
* Суммы покупок по датам
[1270, 8413, 9028, 3703, 5739, 4095, 295, 4944, 5723, 3701, 4471, 651, 7037, 4274, 6275, 4988, 6930, 2971, 6592, 2004, 2822, 519, 3406, 2732, 5015, 2008, 316, 6333, 5700, 2887]

## 3.1 Найдите, какая выручка у компании в ноябре.
## Используйте list comprehensions

In [12]:
date = ['2021-09-14', '2021-12-15', '2021-09-08',
        '2021-12-05', '2021-10-09', '2021-09-30',
        '2021-12-22', '2021-11-29', '2021-12-24',
        '2021-11-26', '2021-10-27', '2021-12-18',
        '2021-11-09', '2021-11-23', '2021-09-27',
        '2021-10-02', '2021-12-27', '2021-09-20',
        '2021-12-13', '2021-11-01', '2021-11-09',
        '2021-12-06', '2021-12-08', '2021-10-09',
        '2021-10-31', '2021-09-30', '2021-11-09',
        '2021-12-13', '2021-10-26', '2021-12-09']

payment = [1270, 8413, 9028, 3703, 5739, 4095,
           295, 4944, 5723, 3701, 4471, 651,
           7037, 4274, 6275, 4988, 6930, 2971,
           6592, 2004, 2822, 519, 3406, 2732,
           5015, 2008, 316, 6333, 5700, 2887]

In [13]:
total_list = {p: date[d] for d, p in enumerate(payment)}

In [14]:
total_list

{1270: '2021-09-14',
 8413: '2021-12-15',
 9028: '2021-09-08',
 3703: '2021-12-05',
 5739: '2021-10-09',
 4095: '2021-09-30',
 295: '2021-12-22',
 4944: '2021-11-29',
 5723: '2021-12-24',
 3701: '2021-11-26',
 4471: '2021-10-27',
 651: '2021-12-18',
 7037: '2021-11-09',
 4274: '2021-11-23',
 6275: '2021-09-27',
 4988: '2021-10-02',
 6930: '2021-12-27',
 2971: '2021-09-20',
 6592: '2021-12-13',
 2004: '2021-11-01',
 2822: '2021-11-09',
 519: '2021-12-06',
 3406: '2021-12-08',
 2732: '2021-10-09',
 5015: '2021-10-31',
 2008: '2021-09-30',
 316: '2021-11-09',
 6333: '2021-12-13',
 5700: '2021-10-26',
 2887: '2021-12-09'}

In [15]:
from collections import defaultdict

In [16]:
total_list = defaultdict(set)

In [17]:
for d, p in zip(date, payment):
    total_list[d].add(p)

In [18]:
total_list

defaultdict(set,
            {'2021-09-14': {1270},
             '2021-12-15': {8413},
             '2021-09-08': {9028},
             '2021-12-05': {3703},
             '2021-10-09': {2732, 5739},
             '2021-09-30': {2008, 4095},
             '2021-12-22': {295},
             '2021-11-29': {4944},
             '2021-12-24': {5723},
             '2021-11-26': {3701},
             '2021-10-27': {4471},
             '2021-12-18': {651},
             '2021-11-09': {316, 2822, 7037},
             '2021-11-23': {4274},
             '2021-09-27': {6275},
             '2021-10-02': {4988},
             '2021-12-27': {6930},
             '2021-09-20': {2971},
             '2021-12-13': {6333, 6592},
             '2021-11-01': {2004},
             '2021-12-06': {519},
             '2021-12-08': {3406},
             '2021-10-31': {5015},
             '2021-10-26': {5700},
             '2021-12-09': {2887}})

In [19]:
total_list.items()

dict_items([('2021-09-14', {1270}), ('2021-12-15', {8413}), ('2021-09-08', {9028}), ('2021-12-05', {3703}), ('2021-10-09', {5739, 2732}), ('2021-09-30', {2008, 4095}), ('2021-12-22', {295}), ('2021-11-29', {4944}), ('2021-12-24', {5723}), ('2021-11-26', {3701}), ('2021-10-27', {4471}), ('2021-12-18', {651}), ('2021-11-09', {316, 7037, 2822}), ('2021-11-23', {4274}), ('2021-09-27', {6275}), ('2021-10-02', {4988}), ('2021-12-27', {6930}), ('2021-09-20', {2971}), ('2021-12-13', {6592, 6333}), ('2021-11-01', {2004}), ('2021-12-06', {519}), ('2021-12-08', {3406}), ('2021-10-31', {5015}), ('2021-10-26', {5700}), ('2021-12-09', {2887})])

In [20]:
sorted_tuple = sorted(total_list.items(), key=lambda x: x[0])

In [21]:
sorted_tuple

[('2021-09-08', {9028}),
 ('2021-09-14', {1270}),
 ('2021-09-20', {2971}),
 ('2021-09-27', {6275}),
 ('2021-09-30', {2008, 4095}),
 ('2021-10-02', {4988}),
 ('2021-10-09', {2732, 5739}),
 ('2021-10-26', {5700}),
 ('2021-10-27', {4471}),
 ('2021-10-31', {5015}),
 ('2021-11-01', {2004}),
 ('2021-11-09', {316, 2822, 7037}),
 ('2021-11-23', {4274}),
 ('2021-11-26', {3701}),
 ('2021-11-29', {4944}),
 ('2021-12-05', {3703}),
 ('2021-12-06', {519}),
 ('2021-12-08', {3406}),
 ('2021-12-09', {2887}),
 ('2021-12-13', {6333, 6592}),
 ('2021-12-15', {8413}),
 ('2021-12-18', {651}),
 ('2021-12-22', {295}),
 ('2021-12-24', {5723}),
 ('2021-12-27', {6930})]

### <font color='red'> А дальше я не понял, как из словаря вытащить данные, которые повторяются, к тому же нужно, видимо искать не по значанию, а по символам (11 месяц) в значении. Перерыл информации кучу, но ничего похожего не нашел</font>

## 3.2 Найдите выручку компании в зависимости от месяца
## Для этого напишите функцию, которая на вход принимает список с датами и список с выручкой, а на выходе словарь, где ключи - это месяцы, а значения - это выручка. Используйте аннотирование типов.

### <font color='red'> Не понимаю, как из такой даты вытащить просто месяц и сделать его ключом. Из-за этого не смог дорешать 3.1</font>